# Generated by Django 3.2 on 2022-04-22 00:43

import advertisement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=advertisement.models.upload_location)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalAdvertisement',
            fields=[
                ('baseadvertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.baseadvertisement')),
                ('animal_breed', models.CharField(blank=True, max_length=50)),
                ('animal_age', models.CharField(blank=True, max_length=10)),
                ('Health', models.CharField(blank=True, max_length=100)),
                ('handingover_reason', models.CharField(blank=True, max_length=500)),
            ],
            bases=('advertisement.baseadvertisement',),
        ),
        migrations.CreateModel(
            name='ClothAdvertisement',
            fields=[
                ('baseadvertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.baseadvertisement')),
                ('expiration_date', models.DateField(blank=True, max_length=8, null=True)),
                ('cloth_status', models.CharField(blank=True, max_length=30)),
                ('for_women', models.BooleanField(default=False)),
                ('for_men', models.BooleanField(default=False)),
                ('unlimited', models.BooleanField(default=False)),
            ],
            bases=('advertisement.baseadvertisement',),
        ),
        migrations.CreateModel(
            name='FoodAdvertisement',
            fields=[
                ('baseadvertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.baseadvertisement')),
                ('Food_type', models.CharField(blank=True, max_length=1000)),
                ('expiration_date', models.DateField(blank=True, max_length=8, null=True)),
            ],
            bases=('advertisement.baseadvertisement',),
        ),
        migrations.CreateModel(
            name='ServiceAdvertisement',
            fields=[
                ('baseadvertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisement.baseadvertisement')),
                ('expiration_date', models.DateField(blank=True, max_length=8, null=True)),
            ],
            bases=('advertisement.baseadvertisement',),
        ),
    ]
