# Generated by Django 3.2 on 2022-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_baseadvertisement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodadvertisement',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
