# Generated by Django 3.2 on 2022-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_auto_20220422_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceadvertisement',
            name='service_type',
            field=models.CharField(blank=True, choices=[('dentistry', 'dentistry'), ('medical', 'medical'), ('piping', 'piping'), ('masonry', 'masonry'), ('gardening', 'gardening'), ('vetinery', 'vetinery'), ('teaching', 'teaching'), ('Psychology', 'Psychology')], max_length=20),
        ),
    ]
