# Generated by Django 3.2 on 2022-05-09 08:25

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    BaseAdvertisement = apps.get_model('advertisement', 'BaseAdvertisement')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    new_ct = ContentType.objects.get_for_model(BaseAdvertisement)
    BaseAdvertisement.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('advertisement', '0006_serviceadvertisement_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaladvertisement',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='baseadvertisement',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='clothadvertisement',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='foodadvertisement',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='serviceadvertisement',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='baseadvertisement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_advertisement.baseadvertisement_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
