# Generated by Django 3.2 on 2022-05-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_auto_20220509_0825'),
        ('advertisement', '0008_saved'),
    ]

    operations = [
    ]
