# Generated by Django 3.2 on 2022-05-19 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_merge_0007_auto_20220509_0825_0008_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadvertisement',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
    ]
