# Generated by Django 3.2 on 2022-05-29 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_baseadvertisement_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadvertisement',
            name='ad_expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 5, 5, 39, 374168), null=True),
        ),
    ]
