# Generated by Django 3.2 on 2022-06-05 16:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0011_baseadvertisement_ad_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseadvertisement',
            name='ad_expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 12, 16, 16, 54, 69882), null=True),
        ),
        migrations.AlterField(
            model_name='baseadvertisement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
