# Generated by Django 3.2 on 2022-06-04 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0013_alter_baseadvertisement_ad_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseadvertisement',
            name='ad_expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 12, 1, 32, 40, 178330), null=True),
        ),
    ]
