# Generated by Django 3.2 on 2022-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0014_alter_baseadvertisement_ad_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadvertisement',
            name='mostaarname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
