# Generated by Django 3.2 on 2022-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_baseadvertisement_mostaarname'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadvertisement',
            name='Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
