# Generated by Django 3.2 on 2022-07-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_savedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
