# Generated by Django 3.2 on 2022-03-13 17:26

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import user_account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='a2.jpg', null=True, upload_to=user_account.models.upload_location)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=user_account.models.upload_cover)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('firstname', models.CharField(default='', max_length=40)),
                ('lastname', models.CharField(default='', max_length=40)),
                ('bio', models.CharField(default='', max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_birth', models.DateField(blank=True, default=django.utils.timezone.now, max_length=8)),
                ('province', models.CharField(default='', max_length=30, null=True)),
                ('job', models.CharField(default='', max_length=30, null=True)),
                ('gender', models.CharField(default='male', max_length=7, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
