# Generated by Django 3.2 on 2022-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='', max_length=40, null=True),
        ),
    ]
