# Generated by Django 3.2 on 2022-03-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_auto_20220313_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
