# Generated by Django 3.2 on 2022-03-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20220316_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='education',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
