# Generated by Django 3.2 on 2022-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_auto_20220414_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
