# Generated by Django 3.2 on 2022-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_alter_account_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
