# Generated by Django 3.2 on 2022-06-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_remove_account_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='province',
        ),
        migrations.RemoveField(
            model_name='account',
            name='region',
        ),
    ]
