# Generated by Django 3.2 on 2022-06-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_account_access_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='access_profile',
            field=models.BooleanField(default=False),
        ),
    ]
