# Generated by Django 3.2 on 2022-06-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_account_access_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
