# Generated by Django 3.2 on 2022-06-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_auto_20220610_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='access_profile',
            field=models.BooleanField(default=True),
        ),
    ]
